---

  - name: Configure ELK VM 1 with Docker
    hosts: elk
    remote_user: sysadmin
    become: true
    tasks:

    - name: docker.io
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

    - name: Install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: Install Docker Module
      pip:
        name: docker
        state: present

    - name: Increase Virtual Memory
      command: sysctl -w vm.max_map_count=262144

    - name: Use More Memory
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present
        reload: true

    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: Enable service docker on boot
      systemd:
        name: docker
        enabled: true
